name: Build, Release and NuGet Package

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-pack:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore Dependencies
      run: dotnet restore SkiaSharpControlV2/SkiaSharpControlV2.csproj

    - name: Build Project
      run: dotnet build SkiaSharpControlV2/SkiaSharpControlV2.csproj --configuration Release --no-restore

    - name: Create NuGet Package
      run: dotnet pack SkiaSharpControlV2/SkiaSharpControlV2.csproj --configuration Release --output ./nupkg

    - name: Upload NuGet Artifact
      uses: actions/upload-artifact@v4
      with:
        name: SkiaGrid-NuGet-Package
        path: ./nupkg/*.nupkg
